export const DEFAULT_SHOHIBUL = [
  "Een Sumarni binti Umar",
  "Rizal Nugraha bin Dwi  Priyono dan Keluarga",
  "Itang Dahyar bin Umar dan Keluarga",
  "Kory Anggraeni binti Itang",
  "Citra Maulidiah binti Bakhtiar",
  "Acep Roni bin Umar dan Keluarga",
  "Khusnul Yusran Taufik bin Acep",
  "Yadi Rusmaryadi bin Ewen Ruswandi",
  "Ade Maryati binti Umar",
  "Rezki Novansyah bin Sonny",
  "Vani Marindani binti Yadi",
  "Revandra adhyasta alkhalifi bin rezki novansyah",
  "Rasheza kamila zahra binti rezki novansyah",
  "Rindu Mayangsari Binti Titing Sukarti"
];

export const DEFAULT_RECIPIENTS = [
  "BI APON",
  "BI ISOH",
  "CEP BALAN",
  "MANG AOM",
  "PIAH",
  "BI WATI",
  "CEU ODAH",
  "YAYAH ETI DEDI",
  "YAYAH PA TETEN",
  "CEU ROHAYA",
  "BI ANI",
  "PA IDI",
  "BU AI TIRAI",
  "NYAI",
  "DEDE ASIH",
  "UA TITI",
  "LILIS",
  "EVA/WOWO",
  "ACID",
  "IWAN",
  "EDI",
  "NENG SARAH",
  "CEU EMI",
  "UJANG",
  "DADANG",
  "ENJAH",
  "NENG JAJA",
  "BU IIS",
  "CEU IDA",
  "IMAS",
  "BI ILAH",
  "AJA",
  "IDA C. EUNCAS",
  "MANG ENTANG",
  "CEU ENGKON",
  "U. DOMRET",
  "UMAN",
  "NENG NAI",
  "ETET",
  "C. ENCAS",
  "MANG AMANG",
  "BI YATI",
  "ERNA",
  "BI EKAS",
  "ENENG",
  "ENUNG",
  "DEN WAWAN",
  "BI ISUR",
  "MANG OSO",
  "ABO",
  "UUH",
  "BU IMAS",
  "BU MIMAH",
  "BU IRAH",
  "PA H IMIN",
  "MANG YOYO",
  "RD RUHIYAT",
  "NENG CICI",
  "AI CEU TATI",
  "TINI",
  "IKEU",
  "OPIK",
  "CEU. NEUNEU",
  "UPI",
  "NENG ADIS",
  "BU HJ. ENTIN",
  "BU UKUN",
  "NENG RANI",
  "BU HJ TATIK",
  "MANG ADANG",
  "CEU ETI ODAH",
  "KIKI",
  "PA IDO",
  "TINAH",
  "BI ERAS",
  "YULI",
  "NINING",
  "SARI",
  "ENTI",
  "MANG KOMAR",
  "ENTUT",
  "CEU RODIAH",
  "CEU YUYU",
  "IDA",
  "KIKI/ATE",
  "NANI",
  "TATANG",
  "BU NENENG",
  "PA DADANG",
  "PA H. IDEN",
  "YADI K. ODAN",
  "MANAH",
  "CEU ATIK",
  "CUCU",
  "UCU",
  "NENG DERA",
  "YANI (M. SENA)",
  "NENG PRIDA",
  "BI EULIS",
  "NENG WULAN",
  "BU ATIN",
  "CEU ENOH",
  "DEWI",
  "NENG KINOY",
  "MA ONOH",
  "BI TIA",
  "MA DIAH",
  "AGUS",
  "PA AYEH",
  "JANG JETO",
  "DIDI",
  "MA II",
  "NENG API",
  "RITA",
  "H. ONENG",
  "UJANG",
  "H. ENCANG",
  "H. ENCENG",
  "EWANG",
  "MANG ANAN",
  "BI EMBOT",
  "NENENG",
  "PA ENDING",
  "BI EUNEUNG",
  "IFAN",
  "MAS WIWIN",
  "H. ALI",
  "ENDA",
  "UCU BEAS",
  "BI AAH",
  "JOIS",
  "GEUGEU",
  "MANG AMAN",
  "YATI",
  "NYAI CEU UNA",
  "LINA/ASEP",
  "UJANG (B. EPON)",
  "ONOH",
  "IMAS/EDI",
  "BI AI",
  "EUIS YUYU",
  "TATANG GAS",
  "EPI",
  "BI ADE",
  "AMOH",
  "BI OKOM",
  "BI TUTI",
  "BI ADE",
  "CEU SUMARNI",
  "CEU IYU",
  "BI WATI",
  "LUKI",
  "MANG ENDANG",
  "NANDANG",
  "MA DAIS",
  "ASKA",
  "MANG ENANG",
  "NENG DIAS",
  "BU AI",
  "ENDI",
  "BI OYOH",
  "UJANG DAWEU",
  "ANAH",
  "AMI",
  "AGUS CEU ENDE",
  "ALIT",
  "BU TITIN",
  "P. UJANG / SARAH",
  "ACANG",
  "BU WIWIN",
  "OOM",
  "BI DADAH",
  "NANO",
  "ADE BI ATIK",
  "BU PIAH",
  "DANDAN",
  "FERI",
  "BI KEUIS",
  "UTE",
  "DEDI",
  "IMAS YANTI",
  "HERU",
  "DADI / EEN",
  "AGUS BOBI",
  "NANDANG PANOONGAN",
  "MANG NANA CISARADAN"
];

export const COLOR_PRESETS = [
  {
    name: "Qurban Green (Classic)",
    primary: "#2d5a27",
    secondary: "#fdfbf7",
    border: "#2d5a27",
    banner: "#cbdcc8",
    bannerText: "#2d5a27"
  },
  {
    name: "Royal Emerald",
    primary: "#065f46",
    secondary: "#f0fdf4",
    border: "#065f46",
    banner: "#bbf7d0",
    bannerText: "#065f46"
  },
  {
    name: "Olive Gold",
    primary: "#854d0e",
    secondary: "#fefce8",
    border: "#854d0e",
    banner: "#fef08a",
    bannerText: "#854d0e"
  },
  {
    name: "Midnight Indigo",
    primary: "#1e3a8a",
    secondary: "#f0f9ff",
    border: "#1e3a8a",
    banner: "#bae6fd",
    bannerText: "#1e3a8a"
  },
  {
    name: "Elegant Charcoal",
    primary: "#1f2937",
    secondary: "#f9fafb",
    border: "#374151",
    banner: "#e5e7eb",
    bannerText: "#111827"
  }
];
